//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVanPhongPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThu
    {
        public string MaDT { get; set; }
        public Nullable<System.DateTime> NgBaoCao { get; set; }
        public Nullable<double> TongDT { get; set; }
        public Nullable<int> TongDonHang { get; set; }
        public Nullable<int> TongSPDaBan { get; set; }
    }
}
