//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVanPhongPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.LichSuNhapHangs = new HashSet<LichSuNhapHang>();
            this.KhoHangs = new HashSet<KhoHang>();
        }
    
        public string MaSP { get; set; }
        public int MaLoai { get; set; }
        public string TenSP { get; set; }
        public double Gia { get; set; }
        public string MoTa { get; set; }
        public double GiaBan { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual ICollection<LichSuNhapHang> LichSuNhapHangs { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
        public virtual ICollection<KhoHang> KhoHangs { get; set; }
    }
}
