//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVanPhongPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public string MaTT { get; set; }
        public string MaDH { get; set; }
        public System.DateTime NgayTT { get; set; }
        public double SoTien { get; set; }
        public string PhuongThucTT { get; set; }
        public string TrangThai { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
